// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcB7bDoBXZ0sGlPkI9dqxVXMIhmEz7K0A',
    appId: '1:814750200624:web:b7709f6a61c41875bacef5',
    messagingSenderId: '814750200624',
    projectId: 'bubbl-klz46e',
    authDomain: 'bubbl-klz46e.firebaseapp.com',
    storageBucket: 'bubbl-klz46e.firebasestorage.app',
    measurementId: 'G-S3PLD9J8Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6YRi9o2nHU3ZWt7mo_nj9TX1fqpDEK_0',
    appId: '1:814750200624:android:0bf37c0ad1592caabacef5',
    messagingSenderId: '814750200624',
    projectId: 'bubbl-klz46e',
    storageBucket: 'bubbl-klz46e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxIgc1eB2vKKzWrVjCU8oQpl4KGFKFsb8',
    appId: '1:814750200624:ios:6ea79285f6565af9bacef5',
    messagingSenderId: '814750200624',
    projectId: 'bubbl-klz46e',
    storageBucket: 'bubbl-klz46e.firebasestorage.app',
    iosClientId: '814750200624-qlua36dj4ufe6e1gsl4lh602cfdum6jh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxIgc1eB2vKKzWrVjCU8oQpl4KGFKFsb8',
    appId: '1:814750200624:ios:6ea79285f6565af9bacef5',
    messagingSenderId: '814750200624',
    projectId: 'bubbl-klz46e',
    storageBucket: 'bubbl-klz46e.firebasestorage.app',
    iosClientId: '814750200624-qlua36dj4ufe6e1gsl4lh602cfdum6jh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcB7bDoBXZ0sGlPkI9dqxVXMIhmEz7K0A',
    appId: '1:814750200624:web:c90e1d67368702b5bacef5',
    messagingSenderId: '814750200624',
    projectId: 'bubbl-klz46e',
    authDomain: 'bubbl-klz46e.firebaseapp.com',
    storageBucket: 'bubbl-klz46e.firebasestorage.app',
    measurementId: 'G-F64EJGN4PE',
  );

}